<?php

/* Implementing hook_menu() */

function node_views_menu(){
	$items = array();
	$items['admin/content/node_views'] = array(
		'title'=>'Node views statistics',
		'page callback'=>'node_views_statistics',
		'access callback'=>'user_access',
		'access arguments'=>array('administer access control'),
		);
	$items['admin/config/content/node_views'] = array(
		'title'=>'Node views configuration',
		'description'=>'Configure node views',
		'page callback'=>'node_views_config',
		'access callback'=>'user_access',
		'access arguments'=>array('administer access control'),
		'file'=>'node_views.settings_form.inc',
		);
	return $items;
}

function node_views_statistics(){
	$content = array();

	$content['statistics'] = array(
		'#type'=>'markup',
		'#markup'=>'<p>Here you can see all the nodes total views.</p>',
		);

	return $content;
}

function node_views_node_view($node, $view_mode = 'full', $langcode = NULL){
	$check = node_views_check($node->type);
	if ($check['count_view'] == 1) {
		node_views_update($check['content_type'], $node);
	}
}

function node_views_check($type){
  $result = db_select('node_views_options', 'n')
  ->fields('n', array('content_type', 'count_view'))
  ->condition('content_type', $type)
  ->execute()
  ->fetchAssoc();
  return $result;
}

function node_views_update($type, $node){
  db_merge('node_views_table')
  ->key(array('content_type' => $node->type))
  ->expression('views', 'views + 1')
  ->fields(array(
  	'nid' => $node->nid,
    'content_type' => $node->type,
  ))
  ->execute();
  return true;
}
