<?php

/* Implementing hook_menu() */

function node_views_menu(){
	$items = array();
	$items['admin/content/node_views'] = array(
		'title'=>'Node views statistics',
		'page callback'=>'node_views_statistics',
		'access callback'=>'user_access',
		'access arguments'=>array('administer access control'),
		);
	$items['admin/config/content/node_views'] = array(
		'title'=>'Node views configuration',
		'page callback'=>'node_views_config',
		'access callback'=>'user_access',
		'access arguments'=>array('administer access control'),
		'file'=>'node_views.settings_form.inc',
		);
	return $items;
}

function node_views_statistics(){
	$content = array();

	$content['statistics'] = array(
		'#type'=>'markup',
		'#markup'=>'<p>Here you can see all the nodes total views.</p>',
		);

	return $content;
}
